version: '3.3'
services:
  # Postgres configuration
  postgres: 
    container_name: postgres-auth
    image: postgres:13
    environment: 
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports: 
      - '5432:5432'
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data 
    networks:
      - postgres

# ----------------------------------------------------------------------------------

  # pgAdmin configuration
  pgadmin: 
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - postgres

# ----------------------------------------------------------------------------------

networks:
  postgres:
    driver: bridge
